print("====SELAMAT DATANG DI PEMBAGIAN GAJI KARYAWAN====")
nama = str(input("MASUKAN NAMA ANDA: ")) 
hari_kerja_perbulan = int(31)
hari_kerja = int(input("MASUKKAN HARI KERJA ANDA DALAM SEBULAN: "))
hari_lembur = int(input("MASUKKAN HARI LEMBUR ANDA: "))
upah_lembur = int(50000)
gaji_pokok = int(8000000)
print("NAMA PEGAWAI: ", nama) 
total_gaji = int((hari_kerja/hari_kerja_perbulan)*gaji_pokok+(hari_lembur*upah_lembur))
print("BULAN INI ANDA MENDAPATKAN GAJI SEBESAR Rp. {:,}".format(total_gaji))